# Site settings
title: Darioush Jalali
email: darioush@cs.washington.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm Darioush and you've found my homepage.
  I research software testing, and so should you!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: darioush0
github_username: darioush

# Build settings
markdown: kramdown
